# -----------------------------------------------------------------
# Harrington Capital plc -- Ansible Inventory
# Phase 3: Linux Hardening | Phase 7: Patch Automation
# -----------------------------------------------------------------

[all:vars]
ansible_user=hcadmin
ansible_python_interpreter=/usr/bin/python3

[linux_servers]
HC-APP01 ansible_host=10.0.1.10
HC-MON01 ansible_host=10.0.3.20

[monitoring]
HC-MON01 ansible_host=10.0.3.20

[app_servers]
HC-APP01 ansible_host=10.0.1.10

# Azure VMs (use public IPs after Phase 1 deployment)
[azure_linux]
vm-harrington-prod-app01 ansible_host=REPLACE_WITH_APP01_PUBLIC_IP
vm-harrington-prod-mon01 ansible_host=REPLACE_WITH_MON01_PUBLIC_IP
